[2024-03-23 02:54:19,721: INFO: main: Welcome to custom log]
[2024-03-24 01:24:31,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 01:24:31,638: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 01:24:31,644: INFO: common: created directory at: artifacts]
[2024-03-24 01:24:31,644: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-24 01:24:31,644: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 01:25:38,342: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 04:21:19,616: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-24 04:21:19,625: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 04:21:19,628: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 04:21:19,628: INFO: common: created directory at: artifacts]
[2024-03-24 04:21:19,629: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-24 04:21:19,629: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 04:22:21,084: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 04:22:22,615: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-14 00:58:51,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-14 00:58:52,011: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-14 00:58:52,019: INFO: common: created directory at: artifacts]
[2024-04-14 00:58:52,022: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-14 00:59:52,805: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-02 14:57:34,013: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 14:57:34,029: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 14:57:34,034: INFO: common: created directory at: artifacts]
[2024-05-02 15:14:56,349: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:14:56,363: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:14:56,369: INFO: common: created directory at: artifacts]
[2024-05-02 15:17:26,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:17:26,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:17:26,727: INFO: common: created directory at: artifacts]
[2024-05-02 15:18:14,908: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:18:14,911: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:18:14,912: INFO: common: created directory at: artifacts]
[2024-05-02 15:25:10,200: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:25:10,202: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:25:10,206: INFO: common: created directory at: artifacts]
[2024-05-02 15:25:10,219: INFO: common: created directory at: .]
[2024-05-02 15:25:58,618: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:25:58,621: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:25:58,622: INFO: common: created directory at: artifacts]
[2024-05-02 15:25:58,624: INFO: common: created directory at: .]
[2024-05-02 15:26:08,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:26:08,969: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:26:08,969: INFO: common: created directory at: artifacts]
[2024-05-02 15:26:08,969: INFO: common: created directory at: .]
[2024-05-02 15:27:36,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:27:36,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:27:36,592: INFO: common: created directory at: artifacts]
[2024-05-02 15:27:36,594: INFO: common: created directory at: .]
[2024-05-02 15:29:06,464: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 15:29:06,468: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 15:29:06,470: INFO: common: created directory at: artifacts]
[2024-05-02 15:29:06,471: INFO: common: created directory at: .]
[2024-05-02 15:30:05,251: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-02 15:30:06,572: INFO: builder_impl: Assets written to: .\assets]
[2024-05-02 18:13:22,297: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-02 18:13:22,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 18:13:22,309: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 18:13:22,309: INFO: common: created directory at: artifacts]
[2024-05-02 18:13:22,309: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-02 18:13:22,309: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 18:13:30,444: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 18:13:31,965: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-02 18:16:34,071: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-02 18:16:34,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 18:16:34,071: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 18:16:34,071: INFO: common: created directory at: artifacts]
[2024-05-02 18:16:34,071: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-02 18:16:34,071: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 18:16:42,495: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 18:16:43,357: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-02 19:39:36,588: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-02 19:39:36,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 19:39:36,588: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 19:39:36,603: INFO: common: created directory at: artifacts]
[2024-05-02 19:39:36,603: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-02 19:39:36,603: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 19:39:43,857: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-02 19:39:45,612: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-02 19:39:45,612: INFO: main: *******************]
[2024-05-02 19:39:45,612: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-02 19:39:45,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 19:39:45,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 19:39:45,612: INFO: common: created directory at: artifacts]
[2024-05-02 19:39:45,628: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-02 19:39:46,420: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-02 19:39:47,626: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-02 19:39:47,626: INFO: main: *******************]
[2024-05-02 19:39:47,626: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-02 19:39:47,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-02 19:39:47,626: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-02 19:39:47,626: INFO: common: created directory at: artifacts]
[2024-05-02 19:39:47,626: INFO: common: created directory at: artifacts\training]
[2024-05-02 19:39:48,514: ERROR: main: [WinError 3] Le chemin d�acc�s sp�cifi� est introuvable: 'artifacts\\data_ingestion\\Chest-CT-Scan-data']
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    model_trainer.main()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 20, in main
    training.train_valid_generator()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\components\model_trainer.py", line 38, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] Le chemin d�acc�s sp�cifi� est introuvable: 'artifacts\\data_ingestion\\Chest-CT-Scan-data'
[2024-05-04 15:46:15,743: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-04 15:46:15,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 15:46:15,759: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 15:46:15,759: INFO: common: created directory at: artifacts]
[2024-05-04 15:46:15,759: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-04 15:46:15,759: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-04 15:53:30,502: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-04 15:53:32,073: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-04 15:53:32,088: INFO: main: *******************]
[2024-05-04 15:53:32,088: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-04 15:53:32,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 15:53:32,135: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 15:53:32,135: INFO: common: created directory at: artifacts]
[2024-05-04 15:53:32,135: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-04 15:53:34,053: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-04 15:53:36,065: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-04 15:53:36,066: INFO: main: *******************]
[2024-05-04 15:53:36,066: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-04 15:53:36,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 15:53:36,071: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 15:53:36,071: INFO: common: created directory at: artifacts]
[2024-05-04 15:53:36,071: INFO: common: created directory at: artifacts\training]
[2024-05-04 15:54:37,487: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-04 17:43:34,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 17:43:34,647: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 17:43:34,654: INFO: common: created directory at: artifacts]
[2024-05-04 17:46:00,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 17:46:00,015: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 17:46:00,018: INFO: common: created directory at: artifacts]
[2024-05-04 17:46:17,390: INFO: common: json file saved at: scores.json]
[2024-05-04 17:50:59,796: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-04 17:50:59,835: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-04 17:50:59,843: INFO: common: created directory at: artifacts]
[2024-05-04 17:51:16,437: INFO: common: json file saved at: scores.json]
[2024-05-04 17:51:21,496: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-04 17:51:23,186: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmpg81y028p\model\data\model\assets]
[2024-05-04 17:56:01,908: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionAbortedError(10053, 'Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte', None, 10053, None)': /AzizKorbi/Kidney-Disease-Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/dc9a173974514c56b77ad7394e4ce98f/f1c0cfeebaf34475a65a5e0b0bf607c8/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-05 13:04:19,465: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 13:04:19,496: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 13:04:19,511: INFO: common: created directory at: artifacts]
[2024-05-05 13:04:39,290: INFO: common: json file saved at: scores.json]
[2024-05-05 13:04:45,474: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-05 13:04:47,005: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmpxsmveunk\model\data\model\assets]
[2024-05-05 13:45:33,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 13:45:33,682: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 13:45:33,691: INFO: common: created directory at: artifacts]
[2024-05-05 13:45:51,712: INFO: common: json file saved at: scores.json]
[2024-05-05 13:46:52,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 13:46:52,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 13:46:52,504: INFO: common: created directory at: artifacts]
[2024-05-05 13:47:09,054: INFO: common: json file saved at: scores.json]
[2024-05-05 13:47:53,528: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-05 13:47:53,528: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-05 13:47:53,528: INFO: common: created directory at: artifacts]
[2024-05-05 13:48:09,153: INFO: common: json file saved at: scores.json]
[2024-05-05 13:48:13,808: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-05 13:48:15,103: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmpler5o6kn\model\data\model\assets]
[2024-05-06 11:41:25,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 11:41:25,432: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 11:41:25,440: INFO: common: created directory at: artifacts]
[2024-05-06 11:41:45,981: INFO: common: json file saved at: scores.json]
[2024-05-06 11:41:50,948: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-06 11:41:52,844: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmpr8v4gt2w\model\data\model\assets]
[2024-05-06 15:59:54,645: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-06 15:59:54,661: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 15:59:54,662: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 15:59:54,662: INFO: common: created directory at: artifacts]
[2024-05-06 15:59:54,662: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-06 15:59:54,662: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 16:00:42,723: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 16:00:44,362: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-06 16:00:44,362: INFO: main: *******************]
[2024-05-06 16:00:44,362: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-06 16:00:44,362: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:00:44,362: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:00:44,362: INFO: common: created directory at: artifacts]
[2024-05-06 16:00:44,362: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-06 16:00:45,085: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-06 16:00:46,527: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-06 16:00:46,527: INFO: main: *******************]
[2024-05-06 16:00:46,527: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-06 16:00:46,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:00:46,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:00:46,527: INFO: common: created directory at: artifacts]
[2024-05-06 16:00:46,527: INFO: common: created directory at: artifacts\training]
[2024-05-06 16:01:40,644: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-06 16:01:40,644: INFO: main: *******************]
[2024-05-06 16:01:40,644: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-06 16:01:40,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:01:40,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:01:40,881: INFO: common: created directory at: artifacts]
[2024-05-06 16:01:58,073: INFO: common: json file saved at: scores.json]
[2024-05-06 16:01:58,073: INFO: common: json file saved at: scores.json]
[2024-05-06 16:01:58,073: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-06 16:04:49,248: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-06 16:04:49,248: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:04:49,272: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:04:49,280: INFO: common: created directory at: artifacts]
[2024-05-06 16:04:49,280: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-06 16:04:49,280: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 16:09:27,802: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 16:09:28,895: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-06 16:09:28,895: INFO: main: *******************]
[2024-05-06 16:09:28,895: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-06 16:09:28,895: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:09:28,895: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:09:28,895: INFO: common: created directory at: artifacts]
[2024-05-06 16:09:28,895: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-06 16:09:29,601: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-06 16:09:33,246: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-06 16:09:33,246: INFO: main: *******************]
[2024-05-06 16:09:33,246: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-06 16:09:33,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:09:33,246: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:09:33,246: INFO: common: created directory at: artifacts]
[2024-05-06 16:09:33,246: INFO: common: created directory at: artifacts\training]
[2024-05-06 16:11:16,105: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-06 16:11:16,105: INFO: main: *******************]
[2024-05-06 16:11:16,105: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-06 16:11:16,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:11:16,121: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:11:16,121: INFO: common: created directory at: artifacts]
[2024-05-06 16:11:33,061: INFO: common: json file saved at: scores.json]
[2024-05-06 16:11:33,061: INFO: common: json file saved at: scores.json]
[2024-05-06 16:11:33,061: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-06 16:27:04,879: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 16:27:04,885: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 16:27:04,905: INFO: common: created directory at: artifacts]
[2024-05-06 16:27:27,719: INFO: common: json file saved at: scores.json]
[2024-05-06 16:27:33,234: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-06 16:27:34,733: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmp5a2mijne\model\data\model\assets]
[2024-05-06 16:58:45,588: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-06 16:58:49,273: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmpiro2n7_r\model\data\model\assets]
[2024-05-06 17:01:16,722: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionAbortedError(10053, 'Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte', None, 10053, None)': /AzizKorbi/Kidney-Disease-Classification.mlflow/api/2.0/mlflow-artifacts/artifacts/dc9a173974514c56b77ad7394e4ce98f/6b2d4acf7bdb40409ddc1a6c895f30bd/artifacts/VGG16/data/model/variables/variables.data-00000-of-00001]
[2024-05-06 17:25:21,893: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-06 17:25:21,893: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:25:21,893: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:25:21,909: INFO: common: created directory at: artifacts]
[2024-05-06 17:25:21,909: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-06 17:25:21,909: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 17:33:43,044: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-06 17:33:43,842: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-06 17:33:43,842: INFO: main: *******************]
[2024-05-06 17:33:43,842: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-06 17:33:43,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:33:43,858: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:33:43,858: INFO: common: created directory at: artifacts]
[2024-05-06 17:33:43,858: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-06 17:33:44,563: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-06 17:33:46,929: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-06 17:33:46,929: INFO: main: *******************]
[2024-05-06 17:33:46,929: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-06 17:33:46,929: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:33:46,945: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:33:46,945: INFO: common: created directory at: artifacts]
[2024-05-06 17:33:46,945: INFO: common: created directory at: artifacts\training]
[2024-05-06 17:35:31,310: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-06 17:35:31,310: INFO: main: *******************]
[2024-05-06 17:35:31,310: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-06 17:35:31,325: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:35:31,332: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:35:31,332: INFO: common: created directory at: artifacts]
[2024-05-06 17:35:49,179: INFO: common: json file saved at: scores.json]
[2024-05-06 17:35:49,179: INFO: common: json file saved at: scores.json]
[2024-05-06 17:35:49,179: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-06 17:38:47,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:38:47,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:38:47,270: INFO: common: created directory at: artifacts]
[2024-05-06 17:39:07,612: INFO: common: json file saved at: scores.json]
[2024-05-06 17:41:01,476: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 17:41:01,497: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 17:41:01,497: INFO: common: created directory at: artifacts]
[2024-05-06 17:41:21,346: INFO: common: json file saved at: scores.json]
[2024-05-06 19:54:23,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 19:54:23,453: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 19:54:23,462: INFO: common: created directory at: artifacts]
[2024-05-06 19:54:44,091: INFO: common: json file saved at: scores.json]
[2024-05-06 20:00:01,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-06 20:00:01,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-06 20:00:01,169: INFO: common: created directory at: artifacts]
[2024-05-06 20:00:23,204: INFO: common: json file saved at: scores.json]
[2024-05-07 09:08:42,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:08:42,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:08:42,741: INFO: common: created directory at: artifacts]
[2024-05-07 09:09:02,848: INFO: common: json file saved at: scores.json]
[2024-05-07 09:09:08,432: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-07 09:09:10,594: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmp_y_kbxq_\model\data\model\assets]
[2024-05-07 09:14:11,362: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:14:11,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:14:11,394: INFO: common: created directory at: artifacts]
[2024-05-07 09:14:31,202: INFO: common: json file saved at: scores.json]
[2024-05-07 09:14:33,786: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-07 09:14:36,392: INFO: builder_impl: Assets written to: C:\Users\aziz\AppData\Local\Temp\tmprbp_ozcw\model\data\model\assets]
[2024-05-07 09:20:17,088: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-07 09:20:17,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:20:17,088: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:20:17,088: INFO: common: created directory at: artifacts]
[2024-05-07 09:20:17,088: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-07 09:20:17,088: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-07 09:22:17,626: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-07 09:22:18,676: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-07 09:22:18,676: INFO: main: *******************]
[2024-05-07 09:22:18,676: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-07 09:22:18,676: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:22:18,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:22:18,676: INFO: common: created directory at: artifacts]
[2024-05-07 09:22:18,676: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-07 09:22:19,524: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-07 09:22:21,372: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-07 09:22:21,372: INFO: main: *******************]
[2024-05-07 09:22:21,390: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-07 09:22:21,390: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:22:21,390: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:22:21,390: INFO: common: created directory at: artifacts]
[2024-05-07 09:22:21,390: INFO: common: created directory at: artifacts\training]
[2024-05-07 09:24:05,952: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-07 09:24:05,952: INFO: main: *******************]
[2024-05-07 09:24:05,952: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-07 09:24:05,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-07 09:24:06,030: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-07 09:24:06,094: INFO: common: created directory at: artifacts]
[2024-05-07 09:24:23,954: INFO: common: json file saved at: scores.json]
[2024-05-07 09:24:23,954: INFO: common: json file saved at: scores.json]
[2024-05-07 09:24:23,954: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-08 17:35:16,598: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-05-08 17:35:16,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 17:35:16,605: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 17:35:16,606: INFO: common: created directory at: artifacts]
[2024-05-08 17:35:16,608: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 17:35:16,608: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 17:53:18,571: ERROR: stage_01_data_ingestion: ("Connection broken: ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None)", ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None))]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 737, in _error_catcher
    yield
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 862, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 845, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 935, in read
    data = self._raw_read(amt)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 891, in _raw_read
    self._fp.close()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 764, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None)", ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 25, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\gdown\download.py", line 344, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None)", ConnectionAbortedError(10053, 'Une connexion �tablie a �t� abandonn�e par un logiciel de votre ordinateur h�te', None, 10053, None))
[2024-05-08 17:53:33,441: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-05-08 17:53:33,443: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 17:53:33,447: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 17:53:33,448: INFO: common: created directory at: artifacts]
[2024-05-08 17:53:33,448: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 17:53:33,448: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 17:57:47,525: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 17:57:48,552: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-05-08 18:01:23,021: INFO: stage_02_prepare_base_model: *******************]
[2024-05-08 18:01:23,021: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 18:01:23,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:01:23,028: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:01:23,030: INFO: common: created directory at: artifacts]
[2024-05-08 18:01:23,031: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 18:01:23,815: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 18:01:25,498: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 18:06:11,098: INFO: stage_02_prepare_base_model: *******************]
[2024-05-08 18:06:11,098: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 18:06:11,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:06:11,114: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:06:11,114: INFO: common: created directory at: artifacts]
[2024-05-08 18:06:11,114: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 18:06:11,615: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 18:06:13,184: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 18:06:19,623: INFO: stage_03_model_trainer: *******************]
[2024-05-08 18:06:19,623: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2024-05-08 18:06:19,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:06:19,623: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:06:19,623: INFO: common: created directory at: artifacts]
[2024-05-08 18:06:19,623: INFO: common: created directory at: artifacts\training]
[2024-05-08 18:08:12,054: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-08 18:15:17,059: INFO: stage_03_model_trainer: *******************]
[2024-05-08 18:15:17,059: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2024-05-08 18:15:17,059: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:15:17,059: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:15:17,059: INFO: common: created directory at: artifacts]
[2024-05-08 18:15:17,059: INFO: common: created directory at: artifacts\training]
[2024-05-08 18:17:08,010: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-08 18:17:19,336: INFO: stage_04_model_evaluation: *******************]
[2024-05-08 18:17:19,336: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-08 18:17:19,336: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:17:19,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:17:19,336: INFO: common: created directory at: artifacts]
[2024-05-08 18:17:37,785: INFO: common: json file saved at: scores.json]
[2024-05-08 18:17:37,801: INFO: common: json file saved at: scores.json]
[2024-05-08 18:17:37,801: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-08 18:56:26,433: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-08 18:56:26,433: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:56:40,246: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:56:40] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:03:50,812: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-08 19:03:50,910: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:03:50] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-08 19:07:14,566: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:07:14] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:08:00,990: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:08:00] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:09:31,446: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-08 19:09:31,446: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:09:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-08 19:11:14,025: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-08 19:11:14,025: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 19:11:33,865: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:11:33] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:12:02,329: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-08 19:12:02,329: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:12:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-08 19:13:13,020: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-08 19:13:13,020: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 19:13:25,197: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:13:25] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:16:04,598: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-08 19:16:04,615: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:16:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-09 13:48:31,152: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-09 13:48:31,152: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 13:49:35,818: INFO: _internal: 127.0.0.1 - - [09/May/2024 13:49:35] "GET / HTTP/1.1" 200 -]
[2024-05-09 13:50:18,170: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-09 13:50:18,354: INFO: _internal: 127.0.0.1 - - [09/May/2024 13:50:18] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-09 13:52:40,510: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-09 13:52:40,510: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 13:53:01,389: INFO: _internal: 127.0.0.1 - - [09/May/2024 13:53:01] "GET / HTTP/1.1" 200 -]
[2024-05-09 13:53:10,670: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 47, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-09 13:53:10,687: INFO: _internal: 127.0.0.1 - - [09/May/2024 13:53:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-09 14:01:56,208: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-09 14:01:56,208: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 14:02:08,192: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:02:08] "GET / HTTP/1.1" 200 -]
[2024-05-09 14:02:21,720: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:02:21] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 14:02:35,222: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:02:35] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 14:02:52,256: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:02:52] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 14:04:16,939: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:04:16] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 14:06:51,547: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.8.231:8081]
[2024-05-09 14:06:51,547: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 14:07:03,486: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:07:03] "GET / HTTP/1.1" 200 -]
[2024-05-09 14:07:13,706: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:07:13] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 14:07:44,172: INFO: _internal: 127.0.0.1 - - [09/May/2024 14:07:44] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 19:11:43,114: INFO: _internal: 127.0.0.1 - - [09/May/2024 19:11:43] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 21:21:11,532: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.80.8:8081]
[2024-05-09 21:21:11,532: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 21:21:24,780: INFO: _internal: 127.0.0.1 - - [09/May/2024 21:21:24] "GET / HTTP/1.1" 200 -]
[2024-05-09 21:31:18,444: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8081
 * Running on http://192.168.80.8:8081]
[2024-05-09 21:31:18,444: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 21:31:30,297: INFO: _internal: 127.0.0.1 - - [09/May/2024 21:31:30] "GET / HTTP/1.1" 200 -]
[2024-05-09 21:31:40,636: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 47, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aziz\desktop\kidney_disease_classification\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 21, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\aziz\miniconda3\envs\kidney\lib\site-packages\PIL\Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001FD83632590>
[2024-05-09 21:31:40,652: INFO: _internal: 127.0.0.1 - - [09/May/2024 21:31:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
